#!/bin/sh

mkdir -p /tmp/plumitranscodetmp
VIDEO_FILE=/tmp/plumitranscodetmp/wget.`date +%s`
wget $1 -O $VIDEO_FILE
chmod 700 $VIDEO_FILE
ffmpeg -i "$VIDEO_FILE" -vf scale="ceil(a*480)+mod(ceil(a*480)\,2):480" -f image2 -ss 8 -vframes 1 "$2"
RET=$?
rm $VIDEO_FILE
exit $RET
