#!/bin/sh

mkdir -p /tmp/plumitranscodetmp
VIDEO_FILE=/tmp/plumitranscodetmp/wget.`date +%s`
wget $1 -O $VIDEO_FILE
chmod 700 $VIDEO_FILE
ffmpeg -y -i "$VIDEO_FILE" -vf "scale=ceil(a*240)+mod(ceil(a*240)\,2):240" -r 25 -threads 0 -ar 44100 -vcodec libx264 -crf 25 -acodec aac -ab 64k -f mp4 "$2"
RET=$?
qt-faststart "$2" "${2}.fst"
mv "${2}.fst" "$2"
rm $VIDEO_FILE
exit $RET
