#!/bin/sh
PATH=.:./bin:$PATH
ffmpeg -y -i "$1" -vf "scale=-1:480" -threads 0 -r 25 -ar 44100 -vcodec libx264 -crf 22 -acodec libfaac -ab 64k -f mp4 "$2"
qt-faststart "$2" "${2}.fst"
mv "${2}.fst" "$2"
