#!/bin/sh
PATH=.:./bin:$PATH
ffmpeg -y -i "$1" -s 320x240 -r 25 -threads 0 -ar 44100 -vcodec libx264 -vpre hq -crf 25 -acodec libfaac -ab 64k -f mp4 "$2"
qt-faststart "$2" "${2}.fst"
mv "${2}.fst" "$2"
