#!/bin/sh
PATH=.:./bin:$PATH:./ffmpeg/bin:$PATH
LD_LIBRARY_PATH=./ffmpeg/parts/vorbis-build/lib:./ffmpeg/parts/theora-build/lib:./ffmpeg/parts/ffmpeg-build/lib:./ffmpeg/parts/x264-build/lib:./ffmpeg/parts/faac-build/lib:./ffmpeg/parts/faad-build/lib:./ffmpeg/parts/lame-build/lib:./ffmpeg/parts/vpx-build/lib:./ffmpeg/parts/ogg-build/lib', '--extra-ldflags=-I./ffmpeg/parts/mp4v2-build/lib
export LD_LIBRARY_PATH
mkdir -p /tmp/plumitranscodetmp
VIDEO_FILE=/tmp/plumitranscodetmp/wget.`date +%s`
wget "$1" -O $VIDEO_FILE
chmod 700 $VIDEO_FILE
ffmpeg -y -i "$VIDEO_FILE" -threads 0 -r 25 -threads 0 -ar 44100 -acodec libvorbis -crf 25 -ab 64k -vf scale="ceil(a*240)+mod(ceil(a*240)\,2):240" "$2"
RET=$?
rm $VIDEO_FILE
exit $RET

