#!/bin/sh

mkdir -p /tmp/plumitranscodetmp
VIDEO_FILE=/tmp/plumitranscodetmp/wget.`date +%s`
wget "$1" -O $VIDEO_FILE
chmod 700 $VIDEO_FILE
ffmpeg -y -i "$VIDEO_FILE" -threads 0 -r 25 -threads 0 -ac 2 -ar 44100 -acodec libvorbis -crf 25 -ab 64k -vf scale="ceil(a*240)+mod(ceil(a*240)\,2):240" "$2"
RET=$?
rm $VIDEO_FILE
exit $RET

